name: Continuous Integration

# This workflow is triggered on pushes and pull requests to the main branch.
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Use Node.js setup
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20" # Specify the Node.js version you are using

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run your test script
      - name: Run test
        run: npm run test

    # You can add additional steps as needed
